title: trafficking.Africa
description: The Human Trafficking Data Observatory is an investigative data project into modern slavery in southern Africa. 
author: trafficking.AFRICA by Code for Africa

url: https://trafficking.africa 
enforce_ssl: trafficking.Africa

tw_url: https://twitter.com/code4africa
fb_url: https://web.facebook.com/CodeForAfrica
gh_url: https://github.com/CodeForAfrica
md_url: https://medium.com/code-for-africa
ig_url: https://www.instagram.com/p/BjfrFfmlGKJ/
giz_url: https://www.data4sdgs.org/


google_analytics: UA-44795600-44
